# -*- coding: utf-8 -*-
"""
Tests for the Moss et al. (2013) surface rupture probability models.

Golden-truth values are pinned to the oq-pfdha reference implementation
(openquake.fdha.primary_surf_rup.moss2013.Moss2013PrimarySR called with the
matching ``style`` and ``vs30`` arguments), logistic
P = 1 / (1 + exp(a - b*mag)) with stiff (Vs30 > 600) and soft branches.

The mixed-array Vs30 golden values were generated by calling the scalar
reference implementation element-by-element (the reference cannot take an
array Vs30), so they pin the vectorized np.where branch selection.
"""
import unittest

import numpy as np

from openquake.hazardlib.contexts import RuptureContext
from openquake.fdha.primary_surf_rup.moss2013 import (
    Moss2013PrimarySR_Reverse,
    Moss2013PrimarySR_SS,
)

MAGS = np.array([5.0, 5.5, 6.0, 6.5, 7.0, 7.5])
# Mixed soft (<=600) / stiff (>600) values, one per magnitude.
VS30_MIXED = np.array([300., 700., 500., 900., 400., 1000.])


class Moss2013ReverseTestCase(unittest.TestCase):
    """Tests for Moss2013PrimarySR_Reverse."""

    def setUp(self):
        self.model = Moss2013PrimarySR_Reverse()

    def test_golden_truth_soft_scalar(self):
        # Pinned to the oq-pfdha reference (style='reverse', vs30=400).
        expected = np.array([
            0.1090190897442952, 0.15638174320883305,
            0.2192572520878716, 0.29846879370155865,
            0.3919316097399709, 0.49405028084392505,
        ])
        got = self.model.get_prob(
            RuptureContext([('mag', MAGS), ('vs30', 400.)]))
        np.testing.assert_allclose(got, expected, rtol=1e-10)

    def test_golden_truth_stiff_scalar(self):
        # Pinned to the oq-pfdha reference (style='reverse', vs30=800).
        expected = np.array([
            0.036368708339403026, 0.0991013233327167,
            0.24277965964595982, 0.48306897570959073,
            0.7314516207339739, 0.888126955145692,
        ])
        got = self.model.get_prob(
            RuptureContext([('mag', MAGS), ('vs30', 800.)]))
        np.testing.assert_allclose(got, expected, rtol=1e-10)

    def test_golden_truth_mixed_array(self):
        # Pinned to the oq-pfdha reference (style='reverse'), evaluated
        # element-by-element over VS30_MIXED.
        expected = np.array([
            0.1090190897442952, 0.0991013233327167,
            0.2192572520878716, 0.48306897570959073,
            0.3919316097399709, 0.888126955145692,
        ])
        got = self.model.get_prob(
            RuptureContext([('mag', MAGS), ('vs30', VS30_MIXED)]))
        np.testing.assert_allclose(got, expected, rtol=1e-10)


class Moss2013SSTestCase(unittest.TestCase):
    """Tests for Moss2013PrimarySR_SS."""

    def setUp(self):
        self.model = Moss2013PrimarySR_SS()

    def test_golden_truth_soft_scalar(self):
        # Pinned to the oq-pfdha reference (style='strike-slip', vs30=400).
        expected = np.array([
            0.07372699490804246, 0.17439407989915842,
            0.3592087603660309, 0.5980147445203107,
            0.7978966697444411, 0.912870618290998,
        ])
        got = self.model.get_prob(
            RuptureContext([('mag', MAGS), ('vs30', 400.)]))
        np.testing.assert_allclose(got, expected, rtol=1e-10)

    def test_golden_truth_stiff_scalar(self):
        # Pinned to the oq-pfdha reference (style='strike-slip', vs30=800).
        expected = np.array([
            0.10205471917615401, 0.22246653484912027,
            0.4187029941132406, 0.6445459204228989,
            0.8203027516146936, 0.9199486831756549,
        ])
        got = self.model.get_prob(
            RuptureContext([('mag', MAGS), ('vs30', 800.)]))
        np.testing.assert_allclose(got, expected, rtol=1e-10)

    def test_golden_truth_mixed_array(self):
        # Pinned to the oq-pfdha reference (style='strike-slip'), evaluated
        # element-by-element over VS30_MIXED.
        expected = np.array([
            0.07372699490804246, 0.22246653484912027,
            0.3592087603660309, 0.6445459204228989,
            0.7978966697444411, 0.9199486831756549,
        ])
        got = self.model.get_prob(
            RuptureContext([('mag', MAGS), ('vs30', VS30_MIXED)]))
        np.testing.assert_allclose(got, expected, rtol=1e-10)
